export type GroupInfoType ={
    group_id:string;
    name:string;
    face_url:string;
    notification:string;
    introduction:string;
    no_show_normal_member:number;
    no_show_all_member:number;
    show_qrcode_by_normal:number;
    join_need_apply:number;
    ban_remove_by_normal:number;
    mute_all_member:number;
    is_topchat:number
    is_disturb:number;
    is_topannocuncement:number
    is_open_admin_list:number
    is_open_admin_icon:number
    is_open_group_id:number
	is_display_nickname_open:number
    group_send_limit:number
};