export default DATA = [
  {
    type: '',
    avatar: '',
    name: '张三',
    status: 'online',
    lastMsgTime: '9:32',
    lastMsgContent: 'Hi,你好。',
    lastMsgType: 'normal',
    unreadcount: 0,
  },
  {
    type: '',
    avatar: '',
    name: '李四',
    status: 'offline',
    lastMsgTime: '9:32',
    lastMsgContent: 'Hi,你好。',
    lastMsgType: 'normal',
    unreadcount: 0,
  },
  {
    type: '',
    avatar: '',
    name: '王五',
    status: 'busy',
    lastMsgTime: '9:32',
    lastMsgContent: 'Hi,你好。',
    lastMsgType: 'normal',
    unreadcount: 0,
  },
  {
    type: '',
    avatar: '',
    name: '赵六',
    status: 'unknown',
    lastMsgTime: '9:32',
    lastMsgContent: 'Hi,你好。',
    lastMsgType: 'normal',
    unreadcount: 0,
  },
  {
    type: '',
    avatar: '',
    name: '孙七',
    status: 'online',
    lastMsgTime: '9:32',
    lastMsgContent: 'Hi,你好。',
    lastMsgType: 'normal',
    unreadcount: 0,
  },
  {
    type: '',
    avatar: '',
    name: '周八',
    status: 'online',
    lastMsgTime: '9:32',
    lastMsgContent: 'Hi,你好。',
    lastMsgType: 'normal',
    unreadcount: 0,
  },
  {
    type: '',
    avatar: '',
    name: '吴九',
    status: 'online',
    lastMsgTime: '9:32',
    lastMsgContent: 'Hi,你好。',
    lastMsgType: 'normal',
    unreadcount: 0,
  },
  {
    type: '',
    avatar: '',
    name: '郑十',
    status: 'online',
    lastMsgTime: '9:32',
    lastMsgContent: 'Hi,你好。',
    lastMsgType: 'normal',
    unreadcount: 0,
  },
];
